# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileLoader
                                 A QGIS plugin
 Download georeferenced parts of tile map servives
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-13
        copyright            : (C) 2022 by Pavel Pereverzev
        email                : pasha004@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TileLoader class from file TileLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_tile_loader import TileLoader
    return TileLoader(iface)
